# This file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Project Ace - Cordova Plugin for Native UI
description: > # this means to ignore newlines until "baseurl:"
  Project Ace is an Apache Cordova plugin that enables you to mix native UI and native code with your JavaScript and HTML. Create cross-platform Android and iOS apps with truly native UI.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ace.run" # the base hostname & protocol for your site
twitter_username: aceplugin
github_username:  adnathan/ace

# Build settings
markdown: kramdown
